version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - /data/redis/data:/data #数据文件挂载
    ports:
      - 6379:6379
